name: Build Binaries
on: 
  push:
    branches: [main]

permissions: write-all

jobs:
  get-version-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.new_tag }}
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          PRERELEASE: true
      
      - name: Echo Tag to output
        run: |
          echo ${{ steps.tag.outputs.new_tag }}

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4
      
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: uv sync
      
      - name: Execute tests
        run: uv run pytest

  build-binaries:
    runs-on: ${{ matrix.platform }}
    needs: [get-version-tag, test]
    strategy:
      matrix:
        include: 
          - platform: ubuntu-24.04
            name: ubuntu-24.04-x64
          - platform: ubuntu-22.04
            name: ubuntu-22.04-x64
          - platform: ubuntu-24.04-arm
            name: ubuntu-24.04-arm64
          - platform: ubuntu-22.04-arm
            name: ubuntu-22.04-arm64
          - platform: windows-2025
            name: windows-server-2025
          - platform: windows-2022
            name: windows-server-2022
          - platform: macos-15
            name: macos-15-arm64
          - platform: macos-14
            name: macos-14-arm64
          - platform: macos-13
            name: macos-13-x64
    steps:
      - name: Get latest code
        uses: actions/checkout@v4
      
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: uv sync
      
      - name: Set version in pyproject
        run: sed -i 's/version = "1.0.0"/version = "${{ needs.get-version-tag.outputs.tag }}"/g' pyproject.toml

      - name: Print pyproject
        run: cat pyproject.toml

      - name: Build binary
        run: uv run pyinstaller ./docker-webhook.spec
  
      - name: Rename binary
        run: mv dist/docker-webhook dist/docker-webhook-${{ needs.get-version-tag.outputs.tag }}-${{ matrix.name }}

      - name: Upload build result
        uses: actions/upload-artifact@v4
        with:
          path: dist/docker-webhook-*
          name: docker-webhook-${{ needs.get-version-tag.outputs.tag }}-${{ matrix.name }}

  build-wheel:
    runs-on: ubuntu-latest
    needs: [get-version-tag, test]
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: uv sync
      
      - name: Set version in pyproject
        run: sed -i 's/version = "1.0.0"/version = "${{ needs.get-version-tag.outputs.tag }}"/g' pyproject.toml

      - name: Build python wheel
        run: uv build

      - name: Rename python wheel
        run: mv dist/docker_webhook-*.whl dist/docker-webhook-${{ needs.get-version-tag.outputs.tag }}-wheel-py3.whl

      - name: Upload python wheel
        uses: actions/upload-artifact@v4
        with:
          path: dist/docker-webhook-*
          name: docker-webhook-${{ needs.get-version-tag.outputs.tag }}-py3-none-any.whl

  release:
    runs-on: ubuntu-latest
    needs: [build-binaries, get-version-tag]
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: docker-webhook-${{ needs.get-version-tag.outputs.tag }}-*
          path: build-results

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.get-version-tag.outputs.tag }}
          append_body: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            build-results/**
